### ISSUE TITLE
Please provide us with a few screenshots.

### ISSUE THREAD

**Issue by mnishiguchi** [lugolabs/tutorials#1]
I am really interested in this tutorial after I glanced through. But I could not picture in my head, what will this app be like? Just one for final product is fine. Thank you! I learned some techniquesbfrom you.

**Comment by rtsinani** [comment]
Have you tried to run the project on your PC? I like to have real demos on the [website](http://www.lugolabs.com/lugoland), rather than screenshots.

**Comment by mnishiguchi** [comment]
You are absolutely right! Real one is always better.

I just thought in the context of reading the [article](http://www.lugolabs.com/lugoland/articles/20-jquery-ui-autocomplete-with-ruby-on-rails), it can be a little bit more reader friendly with a visual aid.
Maybe I was rushing at that time or lazy at that time. I overlooked the demo. I will look into it.

Thank you @rtsinani
