### ISSUE TITLE
Can't find variable: app

### ISSUE THREAD

**Issue by Lubard** [lugolabs/tutorials#10]
Hi there,
I know it sounds stupid...
but I followed the steps and it showed as ReferenceError: Can't find variable: app

as my controller named: activity_controller
and model: products

and I put the definition of app in app/assets/javascripts/activity.js

Thanks in advance

I solved this one...
but It shows the error "Failed to load resource: the server responded with a status of 500"...
any idea?

**Comment by rtsinani** [comment]
Hey @Lubard, what do the logs say? Looks like an error raised in the controller/model.

**Comment by Lubard** [comment]
Hi @rtsinani, it turns out as the ajax codes went wrong... And I solved it. Apologize for not close it earlier...
