### ISSUE TITLE
when i refresh the page last choosing color was reset

### ISSUE THREAD

**Issue by akshayvinchurkar** [lugolabs/tutorials#4]
when i refresh the page last choosing color was reset i dont want that keep the color

**Comment by rtsinani** [comment]
You could save the color in the browser's [local storage](https://developer.mozilla.org/en-US/docs/Web/API/Window/localStorage) or [cookie](https://developer.mozilla.org/en-US/docs/Web/API/Document/cookie).

**Comment by akshayvinchurkar** [comment]
please help with code
